### ISSUE TITLE
Regression spotted in OCaml 4.11.0

### ISSUE THREAD

**Issue by dinosaure** [mirage/eqaf#29]
It seems that the check tool works for OCaml `4.10.0` and `4.09.0` but it does not work for `4.11.0`. The assembly generated is a bit different and I think, we have a possible regression.

**Comment by dinosaure** [comment]
I can confirm this situation... It's about `find_uint8` and `exists_uint8`. These functions **are not** constant-time according to our tool since `4.11.1`. We need to bisect about assembly emitted and why the compiler has this new behavior.

**Comment by dinosaure** [comment]
I can reproduce errors and it seems related to ocaml/ocaml#9392 which changes the output assembly to something... _bad_. Currently, ocaml@2a4aa7a with a revert of ocaml@83598da (`git revert -m1 83598da`) gives a compiler. With this compiler, the `check` tool works so it's about register allocations.

I'm not sure where is the error and I don't have enough time to go further and understand why this PR change the behavior of `eqaf` about `find_uint8` and `exists_uint8`.

**Comment by dinosaure** [comment]
So I followed this wiki to make a compiler with the revert:
https://github.com/ocaml/ocaml/blob/trunk/HACKING.adoc#basic-workflow

And, on my bare-metal server, I get this result:
```
Random: [|57420;41069;54817;64253;63934;64230;4054;6207;34546;20369;14111;47443;31090;25122;16285;17015;|].
> Start to test Eqaf.equal (B¹).
> Start benchmarks on [fn⁰].
[########################################] 100%
> Start benchmarks on [fn¹].
[########################################] 100%
> Merge results.
> Start linear regression.
> Start to test String.equal (B²).
> Start benchmarks on [fn⁰].
[########################################] 100%
> Start benchmarks on [fn¹].
[########################################] 100%
> Merge results.
> Start linear regression.
Eqaf.equal: 6016.735086 ns/run.
String.equal: 750.031906 ns/run.
B¹ = -3.316357, B² = -741.009612.
1 trial(s) for Eqaf.equal.
> Start to test Eqaf.compare (B¹).
> Start benchmarks on [fn⁰].
[########################################] 100%
> Start benchmarks on [fn¹].
[########################################] 100%
> Merge results.
> Start linear regression.
> Start to test String.compare (B²).
> Start benchmarks on [fn⁰].
[########################################] 100%
> Start benchmarks on [fn¹].
[########################################] 100%
> Merge results.
> Start linear regression.
Eqaf.compare: 30368.877088 ns/run.
String.compare: 203.512545 ns/run.
B¹ = -13.111924, B² = -186.399071.
1 trial(s) for Eqaf.compare.
> Start to test Eqaf.exists_uint8 (B¹).
> Start benchmarks on [fn⁰].
[########################################] 100%
> Start benchmarks on [fn¹].
[########################################] 100%
> Merge results.
> Start linear regression.
> Start to test String.contains (B²).
> Start benchmarks on [fn⁰].
[########################################] 100%
> Start benchmarks on [fn¹].
[########################################] 100%
> Merge results.
> Start linear regression.
Eqaf.exists_uint8: 40254.079338 ns/run.
String.contains: 99.507472 ns/run.
B¹ = 16.841544, B² = 10004.350582.
1 trial(s) for Eqaf.exists.
```

**Comment by dinosaure** [comment]
The error seems related by 2 factors:
- with 4.11.0, the code is slightly bigger than before which can have an impact on alignment/cache
- `Eqaf.exists_uint8` takes a function and this function can operate at a different cache-lines and alignments

In theory, `Eqaf.exists_uint8` is _constant-time_, but in practice and depending on the context, it does not pass our check. Multiples solutions exists:
1) replace `f` by the expected `uint8`. By this way, we ensure that `exists_uint8` is "really" constant time (/cc @cfcs)
2) about `check/check.exe`, use a reference and the same function between two classes instead of two different functions (even if they are constant)

All of this report was done by @stedolan who helps me to find the problem between 4.11.0 and 4.10.0.

**Comment by cfcs** [comment]
exists_uint8 should be constant time in the sense that it doesn't leak the input, no that it runs in constant *wall clock* time :-/
